### ISSUE TITLE
Runtime of range-only example

### ISSUE THREAD

**Issue by tipf** [MarineRoboticsGroup/NF-iSAM#2]
Dear Qiangqiang,
thanks for the code! I tried to implement a simple incremental range-only SLAM example: [range_only_incremental.py](https://github.com/tipf/NF-iSAM/blob/main/example/slam/MUSE/range_only_incremental.py)

Unfortunately is the runtime for later iterations quite high, up to 33 minutes for a single inference run - which seems extremely high compared to the runtime in your paper.
I think that I might have configured something wrong, can you give me a hint?

This is the output of one particular iteration:
```
Identify device:  1656663831.0441024
Got training samples:  1656663831.0478718
Normalized samples:  1656663831.100104
Declare flows:  1656663831.4504805
Declare model:  1656663831.4505668
Start training:  1656663831.4697425
INFO:flows on clique:Iter: 100  , last 50 steps loss change: 0.9659616351127625
INFO:flows on clique:Iter: 150  , last 50 steps loss change: 9.052865982055664
INFO:flows on clique:Iter: 200  , last 50 steps loss change: 0.6190283298492432
INFO:flows on clique:Iter: 250  , last 50 steps loss change: 0.23959338665008545
INFO:flows on clique:Iter: 300  , last 50 steps loss change: 0.11969006061553955
INFO:flows on clique:Iter: 350  , last 50 steps loss change: 0.09165704250335693
INFO:flows on clique:Iter: 400  , last 50 steps loss change: 0.06926238536834717
INFO:flows on clique:Iter: 450  , last 50 steps loss change: 0.05257749557495117
INFO:flows on clique:Iter: 500  , last 50 steps loss change: 0.031087279319763184
INFO:flows on clique:Iter: 550  , last 50 steps loss change: 0.02996671199798584
INFO:flows on clique:Iter: 600  , last 50 steps loss change: 0.013159990310668945
INFO:flows on clique:Iter: 650  , last 50 steps loss change: 0.02326345443725586
INFO:flows on clique:Iter: 700  , last 50 steps loss change: 0.007562994956970215
INFO:flows on clique:Early stopping at iter 700
        Time for clique 1/1: 1724.1584887504578 sec, total time elapsed: 1724.1584889888763 sec, clique_dim is 306
Time for phase 96 inference 1724.4885320663452 sec
        cuda training
```

I run the Experiment on a 1080 Ti, which is heavily utilized:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| 42%   72C    P2   158W / 250W |   9647MiB / 11264MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    419179      C   python                           9643MiB |
+-----------------------------------------------------------------------------+
```

**Comment by tipf** [comment]
Okay, forget my question, marking the landmark variables with `variable_type=VariableType.Landmark` solved the problem.
[range_only_incremental.py#L144](https://github.com/tipf/NF-iSAM/blob/1f1962a952df5e03524e8f93176d3d81e683a700/example/slam/MUSE/range_only_incremental.py#L144)

BTW, is there any general recommendation for the `NFiSAMArgs`? For example for the choice of the `elimination_method`?

**Comment by doublestrong** [comment]
Hi Tim,

Thanks for your interest! It is really great to see your script and datasets :+1: :100: :1st_place_medal: 

The ```elimination_method ``` is indeed a critical parameter for the run time. I would recommend ```pose_first``` for the robustness of the solver for various graph structures. The ```elimination_method ``` returns the variable elimination ordering. A good ordering is dependent on the specific problem being solved. I would encourage you to implement your own elimination methods that lead to smaller cliques. For example, you can change this:
https://github.com/tipf/NF-iSAM/blob/1f1962a952df5e03524e8f93176d3d81e683a700/src/slam/FactorGraphSolver.py#L188

The issue in your first post is related to the variable elimination ordering. I guess the elimination ordering (before your correction) leads to very big cliques so the solver would be expected to take a long time to learn normalizing flows in such a clique. As shown in your first post, the ```clique_dim``` is 306, which is super large. Your correction enables the solver to identify that the landmarks are ```VariableType.Landmark```. Then the landmarks will be eliminated after robot poses given the ```pose_first``` variable ordering. I would expect that the ```clique_dim``` after your correction got smaller.

Thanks.
Qiangqiang

**Comment by tipf** [comment]
Hi Qiangqiang,

usually, I would expect that the `ccolamd` method provides the (approximately) best ordering.
It seems, however, that this method is not supposed to be used:
https://github.com/tipf/NF-iSAM/blob/1f1962a952df5e03524e8f93176d3d81e683a700/src/slam/FactorGraph.py#L8

Is there a reason for not using  `ccolamd` as the default method?

**Comment by doublestrong** [comment]
Hi Tim,

That ```ccolamd``` function does not work robustly yet so it is commented out. The function relies on a 3rd party package so we need to check our wrapper for that package.

**Comment by tipf** [comment]
Thanks a lot for your explanations!
